set working-directory := "../.."

# Run all tests (Python + Rust)
default: python rust
    @echo "✅ Ran tests (Python + Rust)."

# Run Python tests
python:
    @echo "Running Python tests..."
    STARLINGS_DEBUG=1 uv run pytest

# Run only Rust tests
rust:
    @echo "Running Rust core tests..."
    cargo test -p starlings-core

# Internal benchmark runner
_bench:
    @echo "Running Rust core benchmarks..."
    STARLINGS_DEBUG=1 cargo bench -p starlings-core
