name: CD
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Get version from tag
      id: get-version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
    
    - name: Update Rust Cargo.toml version
      run: |
        VERSION=${{ steps.get-version.outputs.version }}
        sed -i "s/^version = .*/version = \"$VERSION\"/" src/rust/starlings-py/Cargo.toml
    
    - name: Upload Cargo.toml
      uses: actions/upload-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/starlings-py/Cargo.toml

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: update-version
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Download Cargo.toml
      uses: actions/download-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/starlings-py/
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install dependencies
      run: just install
    
    - name: Build project
      run: just build
    
    - name: Install cibuildwheel
      run: uv tool install cibuildwheel
    
    - name: Build wheels
      run: uv tool run cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp310-* cp311-* cp312-* cp313-* cp314-*
        CIBW_SKIP: pp* cp36-* cp37-* cp38-* *-win32 *i686* *-musllinux*
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BEFORE_BUILD: "uv tool install maturin"
        CIBW_BUILD_FRONTEND: "build"
        MACOSX_DEPLOYMENT_TARGET: "11.0"
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./wheelhouse/*.whl
        name: wheel-builds-${{ matrix.os }}

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: update-version
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Download Cargo.toml
      uses: actions/download-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/starlings-py/
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install dependencies
      run: just install
    
    - name: Build project
      run: just build
    
    - name: Install maturin
      run: uv tool install maturin
    
    - name: Build source distribution
      run: uv tool run maturin sdist --out dist
    
    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Install dependencies
        run: just install
      
      - name: Build project
        run: just build
      
      - name: Build with MkDocs
        run: uv run mkdocs build
      
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy-package:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist, build-docs]
    environment: release
    permissions:
      id-token: write
    
    steps:
    - name: Download wheel artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: wheel-builds-*
        path: dist
        merge-multiple: true
    
    - name: Download sdist artifact
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  deploy-docs:
    name: Publish to GitHub Pages
    needs: [build-wheels, build-sdist, build-docs]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
