name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    name: test ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v5
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
  
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install dependencies
      run: just install
    
    - name: Build project
      run: just build
    
    - name: Run Python tests
      run: just test python

  test-os:
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
  
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"

    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install dependencies
      run: just install

    - name: Build project
      run: just build
      env:
        RUST_BACKTRACE: 1

    - name: Run Python tests
      run: just test python
    
    - name: Run Rust tests
      run: just test rust

  format-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install dependencies
      run: just install
    
    - name: Build project
      run: just build
    
    - name: Format and lint
      run: just format

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"

      - name: Install just
        uses: extractions/setup-just@v2
        
      - name: Install the project
        run: just install

      - name: Build with MkDocs
        run: uv run mkdocs build

  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"

      - name: Install just
        uses: extractions/setup-just@v2
        
      - name: Build the package
        run: just build


  ci-success:
    needs: [format-and-lint, test-python, test-os, build-docs, build-package]
    runs-on: ubuntu-latest

    steps:
      - name: CI Success
        run: echo "All CI checks passed!"
