name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get version from tag
      id: get-version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
    
    - name: Update pyproject.toml version
      run: |
        VERSION=${{ steps.get-version.outputs.version }}
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
    
    - name: Update Rust Cargo.toml version
      run: |
        VERSION=${{ steps.get-version.outputs.version }}
        sed -i "s/^version = .*/version = \"$VERSION\"/" src/rust/entityframe/Cargo.toml
    
    - name: Upload pyproject.toml
      uses: actions/upload-artifact@v4
      with:
        name: pyproject
        path: pyproject.toml
    
    - name: Upload Cargo.toml
      uses: actions/upload-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/entityframe/Cargo.toml

  build-wheels:
    needs: update-version
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            target: s390x-unknown-linux-gnu
          - os: ubuntu-latest
            target: ppc64le-unknown-linux-gnu
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          # macOS
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download pyproject.toml
      uses: actions/download-artifact@v4
      with:
        name: pyproject
        path: .
    
    - name: Download Cargo.toml
      uses: actions/download-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/entityframe/
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.x'
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
    
    - name: Install maturin
      run: uv tool install maturin
    
    - name: Build wheels
      run: uv tool run maturin build --release --target ${{ matrix.target }} --out dist
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.target }}
        path: dist

  build-sdist:
    needs: update-version
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download pyproject.toml
      uses: actions/download-artifact@v4
      with:
        name: pyproject
        path: .
    
    - name: Download Cargo.toml
      uses: actions/download-artifact@v4
      with:
        name: cargo-toml
        path: src/rust/entityframe/
    
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.x'
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Install maturin
      run: uv tool install maturin
    
    - name: Build source distribution
      run: uv tool run maturin sdist --out dist
    
    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    
    steps:
    - name: Download wheel artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: dist
        merge-multiple: true
    
    - name: Download sdist artifact
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1